//
// Created by mor on 1/23/24.
//

#ifndef UNTITLED_ADVENCEDCLASSIFICATIONLOOP_H
#define UNTITLED_ADVENCEDCLASSIFICATIONLOOP_H
int isPalindrom(int x);
int isArmstrong(int x);
#endif //UNTITLED_ADVENCEDCLASSIFICATIONLOOP_H
